version: '3.7'

services:
  db:
    image: postgres:15
    container_name: aprovamais-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    env_file:
      - .env

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aprovamais-app
    ports:
      - "${PORT}:3001"
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL}
      PORT: ${PORT}
    env_file:
      - .env
    command: npm run dev

volumes:
  postgres_data:
